from langchain_core.callbacks import BaseCallbackHandler
from app.utils.logger import logger 
from app.utils.exception import CustomException


class StreamHandler(BaseCallbackHandler):
    """
    Reusable streaming handler for print LLM output in streams, token by token.
    """
    
    def __init__(self, prefix: str = ""):
        """
        Args:
            prefix (str): Optional text to prefix each token line (e.g., "Answer: ")
        """
        self.prefix = prefix


    def on_llm_new_token(self, token: str, **kwargs) -> None:
        """
        Called by LangChain for every new token generated by the LLM.
        """

        print(f"{self.prefix}{token}", end="", flush=True)

    def on_llm_end(self, response, **kwargs) -> None:
        """
        Called when the LLM finishes generating the response.
        Adds a newline for readability.
        """
        
        print("\n", flush=True)
        logger.info("Streaming finished.")
